# Generated by Django 3.1.2 on 2020-11-06 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduate_year', models.IntegerField()),
            ],
            options={
                'db_table': 'education',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128)),
                ('photo', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'form',
            },
        ),
        migrations.CreateModel(
            name='FormSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.form')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skill')),
            ],
            options={
                'db_table': 'form_skills',
            },
        ),
        migrations.CreateModel(
            name='FormJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.form')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
            ],
            options={
                'db_table': 'form_jobs',
            },
        ),
        migrations.CreateModel(
            name='FormEducations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.education')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.form')),
            ],
            options={
                'db_table': 'form_educations',
            },
        ),
        migrations.AddField(
            model_name='form',
            name='educations',
            field=models.ManyToManyField(blank=True, through='form.FormEducations', to='form.Education'),
        ),
        migrations.AddField(
            model_name='form',
            name='jobs',
            field=models.ManyToManyField(through='form.FormJobs', to='core.Job'),
        ),
    ]
