# Generated by Django 3.1.2 on 2020-10-23 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'achievement',
            },
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'duty',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.CharField(max_length=16)),
                ('ended', models.CharField(max_length=16)),
                ('is_extra', models.BooleanField(default=False)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.specialization')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.university')),
            ],
            options={
                'db_table': 'education',
            },
        ),
        migrations.CreateModel(
            name='ExtraSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'extra_skill',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim', models.TextField()),
            ],
            options={
                'db_table': 'form',
            },
        ),
        migrations.CreateModel(
            name='SoftSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'soft_skill',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.CharField(max_length=16)),
                ('ended', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('duties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.duty')),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='FormSoftSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.form')),
                ('soft_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.softskill')),
            ],
            options={
                'db_table': 'form_soft_skills',
                'unique_together': {('form', 'soft_skill')},
            },
        ),
        migrations.CreateModel(
            name='FormJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.form')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.job')),
            ],
            options={
                'db_table': 'form_jobs',
                'unique_together': {('form', 'job')},
            },
        ),
        migrations.CreateModel(
            name='FormExtraSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.extraskill')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.form')),
            ],
            options={
                'db_table': 'form_extra_skills',
                'unique_together': {('form', 'extra_skill')},
            },
        ),
        migrations.CreateModel(
            name='FormEducations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.education')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.form')),
            ],
            options={
                'db_table': 'form_educations',
                'unique_together': {('form', 'education')},
            },
        ),
        migrations.CreateModel(
            name='FormAchievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.achievement')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.form')),
            ],
            options={
                'db_table': 'form_achievements',
                'unique_together': {('form', 'achievement')},
            },
        ),
        migrations.AddField(
            model_name='form',
            name='achievements',
            field=models.ManyToManyField(through='form.FormAchievements', to='form.Achievement'),
        ),
        migrations.AddField(
            model_name='form',
            name='educations',
            field=models.ManyToManyField(through='form.FormEducations', to='form.Education'),
        ),
        migrations.AddField(
            model_name='form',
            name='extra_skills',
            field=models.ManyToManyField(through='form.FormExtraSkills', to='form.ExtraSkill'),
        ),
        migrations.AddField(
            model_name='form',
            name='jobs',
            field=models.ManyToManyField(through='form.FormJobs', to='form.Job'),
        ),
        migrations.AddField(
            model_name='form',
            name='soft_skills',
            field=models.ManyToManyField(through='form.FormSoftSkills', to='form.SoftSkill'),
        ),
        migrations.AddField(
            model_name='form',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form', to=settings.AUTH_USER_MODEL),
        ),
    ]
