# Generated by Django 3.1.2 on 2020-10-23 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='duties',
        ),
        migrations.CreateModel(
            name='JobDuties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.duty')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.job')),
            ],
            options={
                'db_table': 'job_duties',
                'unique_together': {('job', 'duty')},
            },
        ),
        migrations.AddField(
            model_name='job',
            name='duties',
            field=models.ManyToManyField(through='form.JobDuties', to='form.Duty'),
        ),
    ]
