# Generated by Django 3.1.2 on 2020-10-24 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0008_auto_20201024_1244'),
        ('form', '0002_auto_20201024_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='extra_skills',
            field=models.ManyToManyField(through='form.FormExtraSkills', to='vacancy.Skill'),
        ),
        migrations.AlterField(
            model_name='formextraskills',
            name='extra_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.skill'),
        ),
    ]
