# Generated by Django 3.1.2 on 2020-12-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20201106_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='facebook',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='github',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='linkedin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='telegram',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='vk',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='website',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
