# Generated by Django 3.1.2 on 2021-01-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20201219_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='photo',
        ),
    ]
