# Generated by Django 3.1.2 on 2020-10-24 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20201024_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='description',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='extraskill',
            old_name='description',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='softskill',
            old_name='description',
            new_name='text',
        ),
    ]
