# Generated by Django 3.1.2 on 2021-03-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_remove_form_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
