# Generated by Django 3.1.2 on 2021-04-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20210320_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='about',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
