# Generated by Django 3.1.2 on 2021-04-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_form_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
