# Generated by Django 3.1.2 on 2020-10-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_auto_20201024_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duty',
            old_name='description',
            new_name='text',
        ),
    ]
