# Generated by Django 3.1.2 on 2020-10-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='qualification',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
