# Generated by Django 3.1.2 on 2020-10-20 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('short_name', models.CharField(max_length=100, verbose_name='Короткое название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('technologies', models.TextField(verbose_name='Компетенции')),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.file')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('terms', models.IntegerField(choices=[(1, 'Без зарплаты'), (2, 'С зарплатой'), (3, 'Доля компании')], default=1, verbose_name='Условия участия')),
                ('occupation', models.IntegerField(choices=[(1, '10 часов в неделю'), (2, '20 часов в неделю'), (3, '30 часов в неделю'), (4, '40 часов в неделю')], default=1, verbose_name='Занятость')),
                ('work_format', models.IntegerField(choices=[(1, 'Личное присутствие'), (2, 'Удаленная работа')], default=1, verbose_name='Формат работы')),
                ('participants', models.ManyToManyField(blank=True, to='app.Participant', verbose_name='Участники')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('login', models.CharField(max_length=100, verbose_name='Логин')),
                ('password', models.CharField(max_length=200, verbose_name='Пароль')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='Опыт работы')),
                ('terms', models.IntegerField(choices=[(1, 'Без зарплаты'), (2, 'С зарплатой'), (3, 'Доля компании')], default=1, verbose_name='Условия участия')),
                ('occupation', models.IntegerField(choices=[(1, '10 часов в неделю'), (2, '20 часов в неделю'), (3, '30 часов в неделю'), (4, '40 часов в неделю')], default=1, verbose_name='Занятость')),
                ('work_format', models.IntegerField(choices=[(1, 'Личное присутствие'), (2, 'Удаленная работа')], default=1, verbose_name='Формат работы')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Емейл')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Телефон')),
                ('role', models.IntegerField(blank=True, choices=[(1, 'Участник'), (42, 'Компания')], default=1, null=True, verbose_name='Роль')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliated_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company', verbose_name='Компания')),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.file')),
                ('tags', models.ManyToManyField(to='app.Tag', verbose_name='Тэги')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('vacancies', models.ManyToManyField(blank=True, to='app.Vacancy', verbose_name='Вакансии')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('projects', models.ManyToManyField(blank=True, to='app.Project', verbose_name='Проекты')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='departments',
            field=models.ManyToManyField(blank=True, to='app.Department', verbose_name='Департаменты'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.file'),
        ),
        migrations.AddField(
            model_name='company',
            name='participants',
            field=models.ManyToManyField(blank=True, to='app.Participant', verbose_name='Участники'),
        ),
    ]
