# Generated by Django 3.1.2 on 2020-10-23 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'skill',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('short_description', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('salary', models.IntegerField(blank=True)),
                ('experience', models.IntegerField(blank=True)),
                ('min_points', models.IntegerField(blank=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_vacancy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vacancy',
            },
        ),
        migrations.CreateModel(
            name='VacancySkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.skill')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.vacancy')),
            ],
            options={
                'db_table': 'vacancy_skills',
                'unique_together': {('vacancy', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=models.ManyToManyField(through='vacancy.VacancySkills', to='vacancy.Skill'),
        ),
    ]
