# Generated by Django 3.1.2 on 2020-12-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='jobs',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='short_description',
            field=models.TextField(default='lalalal'),
            preserve_default=False,
        ),
    ]
