# Generated by Django 3.1.2 on 2020-10-23 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancy', '0002_auto_20201023_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='experience',
            new_name='employment_type',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience_type',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='schedule_type',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('ACCEPT', 'ACCEPT'), ('DECLINE', 'DECLINE'), ('NO_ANSWER', 'NO_ANSWER')], default='NO_ANSWER', max_length=16)),
                ('created', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='vacancy.vacancy')),
            ],
            options={
                'db_table': 'request',
            },
        ),
    ]
