# Generated by Django 3.1.2 on 2020-10-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_auto_20201023_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
