# Generated by Django 3.1.2 on 2020-12-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_vacancyviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='views',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='VacancyViews',
        ),
    ]
