# Generated by Django 3.1.2 on 2020-10-23 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_city'),
        ('vacancy', '0004_vacancy_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancySpecializations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.specialization')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.vacancy')),
            ],
            options={
                'db_table': 'vacancy_specializations',
                'unique_together': {('vacancy', 'specialization')},
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='specializations',
            field=models.ManyToManyField(through='vacancy.VacancySpecializations', to='core.Specialization'),
        ),
    ]
