# Generated by Django 3.1.2 on 2020-12-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0004_auto_20201219_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
