# Generated by Django 3.1.2 on 2020-10-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0005_auto_20201024_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
