# Generated by Django 3.1.2 on 2020-10-24 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0006_vacancy_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('link', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='VacancyCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.course')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.vacancy')),
            ],
            options={
                'db_table': 'vacancy_courses',
                'unique_together': {('vacancy', 'course')},
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='courses',
            field=models.ManyToManyField(through='vacancy.VacancyCourses', to='vacancy.Course'),
        ),
    ]
