# Generated by Django 3.1.2 on 2021-03-10 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_delete_file'),
        ('vacancy', '0008_auto_20210310_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='is_external',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='company.company'),
            preserve_default=False,
        ),
    ]
