# Generated by Django 3.1.2 on 2021-03-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0010_vacancy_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='is_external',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='url',
            field=models.CharField(blank=True, default='wef', max_length=128),
            preserve_default=False,
        ),
    ]
