# Generated by Django 3.1.2 on 2020-10-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0012_auto_20201024_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='link',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='min_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
