# Generated by Django 3.1.2 on 2021-04-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0012_auto_20210320_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
