# Generated by Django 3.1.2 on 2020-11-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=32, null=True)),
            ],
            options={
                'db_table': 'telegram_bot',
            },
        ),
    ]
