# Generated by Django 3.1.2 on 2020-11-06 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('logo', models.TextField(blank=True)),
                ('subject', models.TextField()),
                ('state', models.TextField()),
                ('link', models.CharField(blank=True, max_length=256)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='core.city')),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('position', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('experience', models.TextField()),
                ('photo', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='CompanyRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.role')),
            ],
            options={
                'db_table': 'company_roles',
            },
        ),
    ]
