# Generated by Django 3.1.2 on 2020-10-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
        migrations.AddField(
            model_name='company',
            name='city_id',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
