# Generated by Django 3.1.2 on 2020-10-23 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_city'),
        ('company', '0002_auto_20201023_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='city_id',
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='core.city'),
            preserve_default=False,
        ),
    ]
