# Generated by Django 3.1.2 on 2020-11-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20201106_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='experience',
        ),
        migrations.AlterField(
            model_name='role',
            name='photo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
