# Generated by Django 3.1.2 on 2020-12-21 13:47

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20201219_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(upload_to=core.models.get_path_for_file)),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
