# Generated by Django 3.1.2 on 2020-12-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20201221_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.TextField(blank=True),
        ),
    ]
