# Generated by Django 3.1.2 on 2020-12-21 14:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20201221_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=core.models.get_path_for_file)),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
