# Generated by Django 3.1.2 on 2021-01-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20201221_1741'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
