# Generated by Django 3.1.2 on 2021-03-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_delete_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
