# Generated by Django 3.1.2 on 2021-03-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_company_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='url',
            field=models.CharField(blank=True, default='sdf', max_length=128),
            preserve_default=False,
        ),
    ]
