# Generated by Django 3.1.2 on 2021-03-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20210310_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_external',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
