# Generated by Django 3.1.2 on 2021-03-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_company_is_external'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
