# Generated by Django 3.1.2 on 2021-03-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_auto_20210320_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='roles',
            field=models.ManyToManyField(blank=True, through='company.CompanyRoles', to='company.Role'),
        ),
    ]
