# Generated by Django 3.1.2 on 2021-04-10 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_auto_20210410_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='categories',
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='company.category'),
        ),
        migrations.DeleteModel(
            name='CompanyCategories',
        ),
    ]
