# Generated by Django 3.1.2 on 2021-04-12 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category'),
        ('company', '0020_auto_20210410_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='core.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
