# Generated by Django 3.1.2 on 2021-04-12 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category'),
        ('company', '0022_remove_company_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='core.category'),
            preserve_default=False,
        ),
    ]
