# Generated by Django 3.1.2 on 2020-10-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='vk_token',
        ),
    ]
