# Generated by Django 3.1.2 on 2021-01-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_auth', '0002_auto_20201106_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.TextField(blank=True),
        ),
    ]
