# Generated by Django 3.1.2 on 2020-10-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_auth', '0003_auto_20201021_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='course',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='degree',
            field=models.CharField(blank=True, choices=[('BACHELOR', 'BACHELOR'), ('MASTER', 'MASTER')], default='BACHELOR', max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='specialization',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='student_id_type',
            field=models.CharField(blank=True, choices=[('TAB', 'TAB'), ('DIPLOMA', 'DIPLOMA')], default='DIPLOMA', max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='university_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
